server:
  port: 82
spring:
  application:
    name: web-logger-logstash-example
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
logstash:
  logType: JDBC
  sysCode: example-system
  logPath: web-logger-logstash-example.log